import turtle
khamenei= turtle.Turtle()
# khamenei.forward(100)
# khamenei.left(45)
# khamenei.forward(200)
khamenei.begin_fill()
khamenei.color("yellow",'orange')
khamenei.forward(100)
khamenei.left(90)
khamenei.forward(100)
khamenei.left(90)
khamenei.forward(100)
khamenei.left(90)
khamenei.forward(100)
khamenei.left(90)
khamenei.end_fill()
turtle.done()